-- ============================================================================
-- Chat Media — data layer
-- ----------------------------------------------------------------------------
-- Adds media (image + audio) support to the messages table and creates the
-- `chat-media` storage bucket with matching RLS policies.
-- Dependency: 20260604130000_seeded_communities.sql must be applied first.
-- ============================================================================


-- ============================================================================
-- 1. messages — media columns
-- ============================================================================
ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS media_url              text,
  ADD COLUMN IF NOT EXISTS media_type             text
    CHECK (media_type IN ('image', 'audio')),
  ADD COLUMN IF NOT EXISTS media_duration_seconds real,
  ADD COLUMN IF NOT EXISTS media_size_bytes       integer;


-- ============================================================================
-- 2. messages — relax body constraint to allow media-only messages
-- ----------------------------------------------------------------------------
-- Current state: body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000)
-- Target state : body TEXT NULL; body <= 2000 chars when present; at least one
--               of body or media_url must be non-null.
-- ============================================================================

-- 2a. Drop the original body length CHECK (name generated by Postgres as
--     messages_body_check from the inline CHECK in the CREATE TABLE statement).
ALTER TABLE public.messages
  DROP CONSTRAINT IF EXISTS messages_body_check;

-- 2b. Allow body to be NULL (media-only messages have no text).
ALTER TABLE public.messages
  ALTER COLUMN body DROP NOT NULL;

-- 2c. New combined constraint:
--   • When body is present it must be ≤ 2000 chars (no minimum — empty string
--     is prohibited by the app layer, but NULL is allowed for media-only rows).
--   • At least one of body or media_url must be non-null (no content-free rows).
ALTER TABLE public.messages
  ADD CONSTRAINT messages_body_or_media_check
    CHECK (
      (body IS NULL OR char_length(body) <= 2000)
      AND (body IS NOT NULL OR media_url IS NOT NULL)
    );


-- ============================================================================
-- 3. Storage bucket: chat-media
-- ----------------------------------------------------------------------------
-- Public reads; authenticated upload (uid-first path enforced by policy);
-- owner delete (uid-first path). Mirrors the recaps/communities convention.
-- ============================================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'chat-media',
  'chat-media',
  true,
  10485760,
  ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'audio/webm',
    'audio/mpeg',
    'audio/mp4',
    'audio/wav'
  ]
);

CREATE POLICY "Public chat media access"
  ON storage.objects
  FOR SELECT
  USING (bucket_id = 'chat-media');

CREATE POLICY "Auth users upload chat media"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'chat-media'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "Users delete own chat media"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'chat-media'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );
